/**
 * Configuration de graphique du builder-IA — promue ici depuis
 * apps/builder-ia/src/state.ts pour servir de vocabulaire COMMUN (#515) :
 * le builder-IA la produit (action-schema), le dashboard et le studio la
 * consomment (widget `chart` fromBuilder), l'export la traduit en balises
 * dsfr-data-*.
 *
 * apps/builder-ia/src/state.ts re-exporte ces types : les imports existants
 * du builder-IA restent valides.
 */

/** Chart configuration generated by the AI */
export interface ChartConfig {
  type:
    | 'bar'
    | 'line'
    | 'pie'
    | 'doughnut'
    | 'radar'
    | 'horizontalBar'
    | 'scatter'
    | 'gauge'
    | 'kpi'
    | 'map'
    | 'bar-line'
    | 'map-reg'
    | 'map-aca'
    | 'map-monde'
    | 'datalist'
    | 'podium';
  labelField?: string;
  valueField: string;
  valueField2?: string;
  /** Séries supplementaires (format LARGE) : une colonne numerique par série. */
  valueFields?: string[];
  codeField?: string;
  aggregation?: 'sum' | 'avg' | 'count' | 'min' | 'max';
  limit?: number;
  sortOrder?: 'desc' | 'asc';
  title?: string;
  subtitle?: string;
  color?: string;
  color2?: string;
  variant?: 'info' | 'success' | 'warning' | 'error';
  unit?: string;
  palette?: string;
  colonnes?: string;
  pagination?: number;
  where?: string;
  data2?: AggregatedResult[];
}

/** A single aggregated data result */
export interface AggregatedResult {
  label: string;
  value: number;
  code?: string | null;
}
