/**
 * Configuration de graphique — promue ici depuis l'ancien Assistant IA
 * (retire en #1081) pour servir de vocabulaire COMMUN (#515) : le studio la
 * produit (bloc `chart`), le dashboard la consomme (widget `chart`
 * fromBuilder), l'export la traduit en balises dsfr-data-*.
 */

/** Chart configuration generated by the AI */
export interface ChartConfig {
  type:
    | 'bar'
    | 'line'
    | 'pie'
    | 'doughnut'
    | 'radar'
    | 'horizontalBar'
    | 'scatter'
    | 'gauge'
    | 'kpi'
    | 'map'
    | 'bar-line'
    | 'map-reg'
    | 'map-aca'
    | 'map-monde'
    | 'datalist'
    | 'podium';
  labelField?: string;
  valueField: string;
  valueField2?: string;
  /** Séries supplementaires (format LARGE) : une colonne numerique par série. */
  valueFields?: string[];
  codeField?: string;
  aggregation?: 'sum' | 'avg' | 'count' | 'min' | 'max';
  limit?: number;
  sortOrder?: 'desc' | 'asc';
  title?: string;
  subtitle?: string;
  color?: string;
  color2?: string;
  variant?: 'info' | 'success' | 'warning' | 'error';
  unit?: string;
  palette?: string;
  colonnes?: string;
  pagination?: number;
  where?: string;
  data2?: AggregatedResult[];
}

/** A single aggregated data result */
export interface AggregatedResult {
  label: string;
  value: number;
  code?: string | null;
}
