/* eslint-disable */
/**
 * FICHIER GENERE — NE PAS EDITER A LA MAIN.
 *
 * Registre des reperes de l'app sources (#997, ADR-143).
 * Source : les attributs data-repere / data-zone / data-attribut / data-prerequis
 * du balisage (index.html, src/connections/connection-manager.ts, src/connections/grist-explorer.ts, src/editors/table-editor.ts), enrichis par
 * packages/core/custom-elements.json et apps/sources/src/assistant/reperes.config.ts.
 * Regenerer : npm run build:reperes. Controle bloquant : npm run check:reperes.
 */
import type { Repere, RegistreReperes } from '@dsfr-data/shared';

export const REPERES = [
  {"id":"sources.actions","genre":"zone","libelle":"Actions sur les sources","element":"div","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.actions.assistant","genre":"controle","libelle":"Assistant","element":"button","zone":"sources.actions","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.actions.exporter","genre":"controle","libelle":"Exporter","element":"button","zone":"sources.actions","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.actions.importer","genre":"controle","libelle":"Importer","element":"input","zone":"sources.actions","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.actions.nouvelle-connexion","genre":"controle","libelle":"Nouvelle connexion","element":"button","zone":"sources.actions","attributs":[],"prerequis":[],"synonymes":["ajouter une connexion","connecter une API","Grist"],"sources":["apps/sources/index.html"]},
  {"id":"sources.apercu","genre":"zone","libelle":"Aperçu des données","element":"aside","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.apercu.actualiser","genre":"controle","libelle":"Actualiser","element":"button","zone":"sources.apercu","attributs":[],"prerequis":["apercu-ouvert"],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.apercu.builder","genre":"controle","libelle":"Utiliser dans le Builder","element":"button","zone":"sources.apercu","attributs":[],"prerequis":["apercu-ouvert"],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.apercu.en-ligne","genre":"controle","libelle":"En faire un jeu en ligne","element":"button","zone":"sources.apercu","attributs":[],"prerequis":["apercu-ouvert"],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.apercu.exporter-grist","genre":"controle","libelle":"Exporter vers Grist","element":"button","zone":"sources.apercu","attributs":[],"prerequis":["apercu-ouvert"],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.apercu.favori","genre":"controle","libelle":"Ajouter aux favoris","element":"button","zone":"sources.apercu","attributs":[],"prerequis":["apercu-ouvert"],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.apercu.fermer","genre":"controle","libelle":"Fermer","element":"button","zone":"sources.apercu","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.apercu.local","genre":"controle","libelle":"En faire un jeu local","element":"button","zone":"sources.apercu","attributs":[],"prerequis":["apercu-ouvert"],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexion","genre":"zone","libelle":"Nouvelle connexion","element":"div","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexion.annuler","genre":"controle","libelle":"Annuler","element":"button","zone":"sources.connexion","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexion.configuration","genre":"zone","libelle":"Configuration de la connexion","element":"div","zone":"sources.connexion","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexion.configuration.api","genre":"zone","libelle":"API REST","element":"div","zone":"sources.connexion.configuration","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexion.configuration.api.ajouter-en-tete","genre":"controle","libelle":"Ajouter un en-tête","element":"button","zone":"sources.connexion.configuration.api","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexion.configuration.api.chemin","genre":"controle","libelle":"Emplacement des données (optionnel)","element":"input","zone":"sources.connexion.configuration.api","attributs":[],"prerequis":[],"synonymes":["data path","emplacement des données"],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexion.configuration.api.en-tete-nom","genre":"controle","libelle":"Nom de l'en-tête","element":"input","zone":"sources.connexion.configuration.api","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/src/connections/connection-manager.ts"]},
  {"id":"sources.connexion.configuration.api.en-tete-retirer","genre":"controle","libelle":"Supprimer cet en-tête","element":"button","zone":"sources.connexion.configuration.api","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/src/connections/connection-manager.ts"]},
  {"id":"sources.connexion.configuration.api.en-tete-valeur","genre":"controle","libelle":"Valeur de l'en-tête","element":"input","zone":"sources.connexion.configuration.api","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/src/connections/connection-manager.ts"]},
  {"id":"sources.connexion.configuration.api.methode","genre":"controle","libelle":"Méthode HTTP","element":"select","zone":"sources.connexion.configuration.api","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexion.configuration.api.url","genre":"controle","libelle":"URL des données","element":"input","zone":"sources.connexion.configuration.api","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexion.configuration.grist","genre":"zone","libelle":"Base Grist","element":"div","zone":"sources.connexion.configuration","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexion.configuration.grist.cle-api","genre":"controle","libelle":"Clé API","element":"input","zone":"sources.connexion.configuration.grist","attributs":[],"prerequis":[],"synonymes":["clé API","jeton","token"],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexion.configuration.grist.document-public","genre":"controle","libelle":"URL du document public","element":"input","zone":"sources.connexion.configuration.grist","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexion.configuration.grist.public","genre":"controle","libelle":"Document public (sans clé API)","element":"input","zone":"sources.connexion.configuration.grist","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexion.configuration.grist.url","genre":"controle","libelle":"URL du serveur Grist","element":"input","zone":"sources.connexion.configuration.grist","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexion.configuration.nom","genre":"controle","libelle":"Nom de la connexion","element":"input","zone":"sources.connexion.configuration","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexion.configuration.retour","genre":"controle","libelle":"Revenir à la détection par URL","element":"button","zone":"sources.connexion.configuration","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexion.continuer","genre":"controle","libelle":"Continuer","element":"button","zone":"sources.connexion","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexion.detection","genre":"zone","libelle":"Détection par URL","element":"div","zone":"sources.connexion","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexion.detection.manuel","genre":"controle","libelle":"Configurer manuellement","element":"button","zone":"sources.connexion.detection","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexion.detection.url","genre":"controle","libelle":"Adresse du jeu de données","element":"input","zone":"sources.connexion.detection","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexion.enregistrer","genre":"controle","libelle":"Tester et sauvegarder","element":"button","zone":"sources.connexion","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexion.fermer","genre":"controle","libelle":"Fermer","element":"button","zone":"sources.connexion","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.connexions","genre":"zone","libelle":"Connexions","element":"div","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.export-grist","genre":"zone","libelle":"Exporter vers Grist","element":"div","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.export-grist.annuler","genre":"controle","libelle":"Annuler","element":"button","zone":"sources.export-grist","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.export-grist.connexion","genre":"controle","libelle":"Connexion Grist","element":"select","zone":"sources.export-grist","attributs":[],"prerequis":["apercu-ouvert"],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.export-grist.creer","genre":"controle","libelle":"Créer la table","element":"button","zone":"sources.export-grist","attributs":[],"prerequis":["apercu-ouvert"],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.export-grist.document","genre":"controle","libelle":"Document Grist","element":"select","zone":"sources.export-grist","attributs":[],"prerequis":["apercu-ouvert"],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.export-grist.fermer","genre":"controle","libelle":"Fermer","element":"button","zone":"sources.export-grist","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.export-grist.nom-table","genre":"controle","libelle":"Nom de la nouvelle table","element":"input","zone":"sources.export-grist","attributs":[],"prerequis":["apercu-ouvert"],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.jointure","genre":"zone","libelle":"Joindre deux sources","element":"div","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.jointure.annuler","genre":"controle","libelle":"Annuler","element":"button","zone":"sources.jointure","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.jointure.cle","genre":"controle","libelle":"Colonne commune aux deux sources","element":"input","zone":"sources.jointure","attributs":[{"tag":"dsfr-data-join","nom":"on","description":"Clé(s) de jointure. - Clé commune : on=\"code_dept\" - Clé différente : on=\"dept_code=code\" (gauche=droite) - Multi-clé : on=\"annee,code_region\""}],"prerequis":["deux-sources-locales"],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.jointure.enregistrer","genre":"controle","libelle":"Joindre et sauvegarder","element":"button","zone":"sources.jointure","attributs":[],"prerequis":["deux-sources-locales"],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.jointure.fermer","genre":"controle","libelle":"Fermer","element":"button","zone":"sources.jointure","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.jointure.nom","genre":"controle","libelle":"Nom de la source jointe","element":"input","zone":"sources.jointure","attributs":[],"prerequis":["deux-sources-locales"],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.jointure.prefixe","genre":"controle","libelle":"Préfixe pour les champs de B en cas de doublon","element":"input","zone":"sources.jointure","attributs":[{"tag":"dsfr-data-join","nom":"prefix-right","description":"Préfixe pour les champs de la source droite en cas de collision"}],"prerequis":["deux-sources-locales"],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.jointure.source-a","genre":"controle","libelle":"Source A (principale)","element":"select","zone":"sources.jointure","attributs":[],"prerequis":["deux-sources-locales"],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.jointure.source-b","genre":"controle","libelle":"Source B (complémentaire)","element":"select","zone":"sources.jointure","attributs":[],"prerequis":["deux-sources-locales"],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.jointure.type","genre":"controle","libelle":"Type de jointure","element":"select","zone":"sources.jointure","attributs":[{"tag":"dsfr-data-join","nom":"type","description":"Type de jointure : inner | left | right | full"}],"prerequis":["deux-sources-locales"],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.locaux","genre":"zone","libelle":"Jeux de données locaux","element":"div","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.locaux.creer","genre":"controle","libelle":"Créer une source manuelle","element":"button","zone":"sources.locaux","attributs":[],"prerequis":[],"synonymes":["saisir des données","coller du JSON","importer un CSV"],"sources":["apps/sources/index.html"]},
  {"id":"sources.locaux.joindre","genre":"controle","libelle":"Joindre deux sources","element":"button","zone":"sources.locaux","attributs":[],"prerequis":[],"synonymes":["jointure","croiser deux sources","fusionner"],"sources":["apps/sources/index.html"]},
  {"id":"sources.manuelle","genre":"zone","libelle":"Nouvelle source manuelle","element":"div","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.manuelle.annuler","genre":"controle","libelle":"Annuler","element":"button","zone":"sources.manuelle","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.manuelle.csv","genre":"zone","libelle":"Importer un CSV","element":"div","zone":"sources.manuelle","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.manuelle.csv.fichier","genre":"controle","libelle":"Fichier CSV","element":"input","zone":"sources.manuelle.csv","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.manuelle.csv.separateur","genre":"controle","libelle":"Séparateur","element":"select","zone":"sources.manuelle.csv","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.manuelle.enregistrer","genre":"controle","libelle":"Enregistrer","element":"button","zone":"sources.manuelle","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.manuelle.fermer","genre":"controle","libelle":"Fermer","element":"button","zone":"sources.manuelle","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.manuelle.json","genre":"zone","libelle":"Coller du JSON","element":"div","zone":"sources.manuelle","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.manuelle.json.chemin","genre":"controle","libelle":"Chemin vers les données (optionnel)","element":"input","zone":"sources.manuelle.json","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.manuelle.json.contenu","genre":"controle","libelle":"Contenu JSON","element":"textarea","zone":"sources.manuelle.json","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.manuelle.mode-csv","genre":"controle","libelle":"Importer CSV","element":"button","zone":"sources.manuelle","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.manuelle.mode-json","genre":"controle","libelle":"Coller JSON","element":"button","zone":"sources.manuelle","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.manuelle.mode-tableau","genre":"controle","libelle":"Tableau","element":"button","zone":"sources.manuelle","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.manuelle.nom","genre":"controle","libelle":"Nom de la source","element":"input","zone":"sources.manuelle","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.manuelle.tableau","genre":"zone","libelle":"Saisie en tableau","element":"div","zone":"sources.manuelle","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.manuelle.tableau.ajouter-colonne","genre":"controle","libelle":"Ajouter une colonne","element":"button","zone":"sources.manuelle.tableau","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.manuelle.tableau.ajouter-ligne","genre":"controle","libelle":"Ajouter une ligne","element":"button","zone":"sources.manuelle.tableau","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.manuelle.tableau.cellule","genre":"controle","libelle":"Cellule","element":"input","zone":"sources.manuelle.tableau","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html","apps/sources/src/editors/table-editor.ts"]},
  {"id":"sources.manuelle.tableau.colonne","genre":"controle","libelle":"Nom de colonne","element":"input","zone":"sources.manuelle.tableau","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html","apps/sources/src/editors/table-editor.ts"]},
  {"id":"sources.manuelle.tableau.retirer-colonne","genre":"controle","libelle":"Supprimer la colonne","element":"button","zone":"sources.manuelle.tableau","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html","apps/sources/src/editors/table-editor.ts"]},
  {"id":"sources.manuelle.tableau.retirer-ligne","genre":"controle","libelle":"Supprimer la ligne","element":"button","zone":"sources.manuelle.tableau","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html","apps/sources/src/editors/table-editor.ts"]},
  {"id":"sources.table-grist","genre":"zone","libelle":"Créer une table dans Grist","element":"div","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.table-grist.ajouter-colonne","genre":"controle","libelle":"Ajouter une colonne","element":"button","zone":"sources.table-grist","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.table-grist.annuler","genre":"controle","libelle":"Annuler","element":"button","zone":"sources.table-grist","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.table-grist.colonne-nom","genre":"controle","libelle":"Nom de colonne","element":"input","zone":"sources.table-grist","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html","apps/sources/src/connections/grist-explorer.ts"]},
  {"id":"sources.table-grist.colonne-retirer","genre":"controle","libelle":"Supprimer cette colonne","element":"button","zone":"sources.table-grist","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html","apps/sources/src/connections/grist-explorer.ts"]},
  {"id":"sources.table-grist.colonne-type","genre":"controle","libelle":"Type de colonne","element":"select","zone":"sources.table-grist","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html","apps/sources/src/connections/grist-explorer.ts"]},
  {"id":"sources.table-grist.creer","genre":"controle","libelle":"Créer la table","element":"button","zone":"sources.table-grist","attributs":[],"prerequis":["document-grist-choisi"],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.table-grist.fermer","genre":"controle","libelle":"Fermer","element":"button","zone":"sources.table-grist","attributs":[],"prerequis":[],"synonymes":[],"sources":["apps/sources/index.html"]},
  {"id":"sources.table-grist.nom","genre":"controle","libelle":"Nom de la table","element":"input","zone":"sources.table-grist","attributs":[],"prerequis":["document-grist-choisi"],"synonymes":[],"sources":["apps/sources/index.html"]},
] as const satisfies readonly Repere[];

/** Identifiant de repere de l'app : enumeration fermee (outil montrer(), #1003). */
export type RepereId = (typeof REPERES)[number]['id'];

export const REGISTRE: RegistreReperes = {
  app: "sources",
  prefixe: "sources",
  reperes: REPERES,
};
